name: experiments-tc-keras
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.2
  - pip=21.2.2
  - tensorflow-gpu=2.4.1
  - scikit-learn=0.24.2
  - tokenizers=0.10.3
  - pandas=1.1.3
  - pip:
      - tqdm==4.62.3
      - scikit-multilearn==0.2.0
      - regex
      - gensim==4.1.2
      - spacy==3.1.3
      - nltk==3.6.3
      - stop_words
      - torchvision
      - torchtext
