---
NUM_JOBS: -1 # All available cores
MAX_FEATURES: 30000
CV: 10
NB_GRID:
  estimator__alpha: [ 0.01, 0.05, 0.1, 0.25, 0.5, 1.0, 10.0, ]
  estimator__fit_prior: [ true, false ]
SVM_GRID:
  estimator__C: [ 1,2,3,4,5 ]
  estimator__max_iter: [ 1000 ]
DATASET_NAME: "frwiki-3" # name of folder with generated splits (path will be data/generated/{DATASET_NAME})
