PRETRAINED_LM: bert-base-uncased
MODEL_L1: "out/bert4c/bert_l1_concat_cls_3"
MODEL_L2: "out/bert4c/bert_l2_concat_cls_3"

dataset: "bugs"
validation: false
mode: "Multilevel_ML"

L2_REG: 0.01
LEARNING_RATE: 2.0e-4
BATCH_SIZE: 32
TEST_BATCH_SIZE: 32
EPOCHS: 2
CLASS_BALANCED_WEIGHTED_LOSS: false
LABEL: "flattened_label" # Which label to use for classification: "label", "flattened_label"
REMOVE_GARBAGE_TEXT: false

DEVICE: "cuda"
TENSORBOARD: false

EPOCHS_TO_KEEP: 2
SAVE_NON_IMPROVING: false  # Always save all epochs. True also saves non-improving
EARLY_STOPPING:
  monitor_key: "loss"
  patience: 1
  delta: 0.0001
  metrics_trend: "decreasing" # The desired tendency of the metric

# Reload
RELOAD: false
MODEL_FOLDER: "out/multi_level/Multilevel_ML"
PATH_TO_RELOAD: "out/multi_level/Multilevel_ML" # Full path to the model folder (e.g. dump_model) or to the epoch folder

NUM_FOLD: 3
CV_REPEAT: 2