name: experiments-tc
channels:
  - pytorch
  - anaconda
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - fasttext=0.9.2
  - keras=2.6.0
  - keras-preprocessing=1.1.2
  - matplotlib-base=3.4.3
  - numpy-base=1.20.3
  - pandas=1.1.3
  - pip=21.2.2
  - python=3.8.11
  - pytorch=1.9.0
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - tokenizers=0.10.3
  - torchinfo=1.5.3
  - torchmetrics=0.5.1
  - torchtext=0.10.0
  - tqdm=4.62.2
  - transformers=4.10.2
  - pip:
      - gensim==4.1.2
      - keras-applications==1.0.8
      - nltk==3.6.3
      - numpy==1.18.5
      - scikit-multilearn==0.2.0
      - scipy==1.4.1
      - spacy==3.1.3
      - stop-words==2018.7.23
      - tensorboard==2.2.2
