---
device: "cuda:0"
num_seeds: 10

dataset_name: "treviso-market-224_224-seg_augmented_additive" # [treviso-market-224_224]

train:
  network_type: "pre_trained_vit" # ['cnn', 'mobilenet_v2', 'pre_trained_vit']
  epochs: 25
  optimizer: "AdamW" # SGD, Adam, AdamW
  criterion: "CrossEntropyLoss" # NLLLoss, CrossEntropyLoss
  batch_size: 16
  learning_rate: 1.5e-05
  log_every: 1
  evaluate_every: 1
  early_stopping:
    patience: 2
    metrics: "macro_f1"
    metrics_trend: "increasing"
cv:
  k: 5
  use_cv_metadata: false

